In [230]:
import numpy as np
import pandas as pd

In [231]:
from sklearn import datasets

In [232]:
df=datasets.load_digits()

In [233]:
xinput=df.data
ytarget=df.target

In [234]:
xinput.shape

(1797, 64)

In [235]:
ytarget.shape

(1797,)

In [236]:
from sklearn.model_selection import train_test_split

In [237]:
X_train,X_test,y_train,y_test=train_test_split(xinput,ytarget,test_size=.30,random_state=101)

In [238]:
X_train.shape

(1257, 64)

In [239]:
X_test.shape

(540, 64)

In [240]:
y_train.shape

(1257,)

In [241]:
y_test.shape

(540,)

In [242]:
from sklearn.svm import SVC


In [243]:
trainer=SVC(gamma=.001)

In [244]:
learner=trainer.fit(xinput,ytarget)

In [245]:
#ya=y_test

In [246]:
#yp=learner.predict(X_test)

In [247]:
#from sklearn.metrics import accuracy_score,jaccard_similarity_score,classification_report

In [248]:
#from sklearn.metrics import confusion_matrix

In [249]:
#acc=accuracy_score(ya,yp)

In [250]:
#


In [251]:
#jss=jaccard_similarity_score(ya,yp)

In [252]:
#jss

In [253]:
#cm=confusion_matrix(ya,yp)

In [254]:
#cm

In [255]:
#cr=classification_report(ya,yp)

In [256]:
#print(cr)

In [257]:
pwd

'C:\\Users\\xcalibre\\Documents\\data analysis'

In [258]:
from matplotlib import pyplot as plt
from scipy import misc

In [259]:
mytestdata=misc.imread(r"8.jpg")

C:\Users\xcalibre\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.


In [260]:
mytestdata

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [261]:
mytestdata.shape

(256, 256, 3)

In [262]:
imageresize=misc.imresize(mytestdata,(8,8))

C:\Users\xcalibre\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  """Entry point for launching an IPython kernel.


In [263]:
imageresize.shape

(8, 8, 3)

In [264]:
imageresize.dtype

dtype('uint8')

In [265]:
image_float=imageresize.astype(df.images.dtype)

In [266]:
image_float.dtype

dtype('float64')

In [267]:
#down scale
image_scale=misc.bytescale(image_float,high=16,low=0)

C:\Users\xcalibre\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `bytescale` is deprecated!
`bytescale` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
  


In [268]:
image_scale_float=image_scale.astype(df.images.dtype)

In [269]:
image_scale_float

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 8.,  8.,  8.],
        [13., 13., 13.],
        [13., 13., 13.],
        [ 2.,  2.,  2.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 3.,  3.,  3.],
        [10., 10., 10.],
        [ 0.,  0.,  0.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 3.,  3.,  3.],
        [10., 10., 10.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [ 7.,  7.,  7.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [10., 10., 10.],
        [10., 10., 10.],
        [16., 16., 16.],
        [ 5.,  5.,  5.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [15., 15., 15.],
        [12., 12., 12.],
        [11., 11., 11.],
        [ 2.,  2.,  2.],
        [ 0.,  0.

In [270]:
#it is 3d so need to convert to lower dimension
xtestimage=[]
for i in image_scale_float:
    for j in i:
        xtestimage.append(sum(j)/3.0)

In [271]:
type(xtestimage)

list

In [272]:
Mytestimage=np.array(xtestimage)

In [273]:
Myreshapetestimage=Mytestimage.reshape(1,len(Mytestimage))

In [274]:
Myreshapetestimage.shape

(1, 64)

In [275]:
learner.predict(Myreshapetestimage)

array([8])